// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type LeetCode = Collections['leetcode']['schema']['_output']
export declare const leetcode: LeetCode[]

export type Codewars = Collections['codewars']['schema']['_output']
export declare const codewars: Codewars[]

export type HackerRank = Collections['hackerrank']['schema']['_output']
export declare const hackerrank: HackerRank[]

export type Exercism = Collections['exercism']['schema']['_output']
export declare const exercism: Exercism[]
